name: 'Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
        typescript:
          ['~4.7.4', '~4.8.3', '~4.9.5', '~5.0.4', '~5.1.6', '~5.2.2', '~5.3.3', '~5.4.2', 'latest']
    name: Node ${{ matrix.node }} / TS ${{ matrix.typescript }}
    steps:
      - name: ♻️ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 🏗️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install TS at correct version
        run: npm i typescript@${{ matrix.typescript }}

      - name: Run type tests
        run: npm run test-type

      - name: Run format
        run: npm run test-format

      - name: Run unit tests
        run: npm run test-unit

      - name: Run lint tests
        run: npm run test-lint
